Todo.create(title: "Product Roadmap", body: "Complete by next week")
Todo.create(title: "Chat with Derek", body: "Get some time on his calendar")
Todo.create(title: "Talk to Mona Bijoor", body: "Feedback on article")
Todo.create(title: "Call Joey", body: "Or he'll have my guts for garters!")
Todo.create(title: "Register car insurance", body: "Or I'm screwed")
Todo.create(title: "One more todo", body: "And we're done here!")
